services:
  app-service:
    image: crtxtcr/app-service                       # specify name of image on Docker Hub
    restart: "always"                                # auto restart container on crash
    environment:                                     # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "8000:8000"     # expose port 8000 so that applications outside the container can connect to it 
    depends_on:         # only run app-service after auth-service has started
      auth-service:
        condition: service_started

  auth-service:
    image:   crtxtcr/auth-service
    restart: "always"                   # auto restart container on crash
    environment:
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}"
        POSTMARK_AUTH_TOKEN: ${POSTMARK_AUTH_TOKEN}
    ports:
      - "3000:3000"                     # expose :3000 so apps outside container can connect to it
    depends_on:
      - db

  db:
    image:   postgres:15.2-alpine
    restart: "always"                   # auto restart container on crash
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postresql/data

  redis:
    image: redis:7.0-alpine
    restart: "always"
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local

